version: '3'
services:
  dynamics_defend_torrent:
    image: joey1029/defend_cat:1.0.0
    restart: always
    container_name: defend_cat
    ports:
      - 29223:29223
    network_mode: bridge
    volumes:
      - 【修改后的application.yml文件路径】:/application.yml
    # 启动命令【不需要修改】
    command: java -jar /joey/server/pter-1.0.0.jar --spring.config.location=/application.yml
