version: '3'
services:
  defend_cat:
    image: joey1029/defend_cat:1.0.7
    restart: always
    container_name: defend_cat
    ports:
      - 29223:29223
    network_mode: bridge
    volumes:
      - 【修改后的application.yml文件路径】:/application.yml
    # 启动命令【不需要修改】
    command: java -jar /joey/server/pter.jar --spring.config.location=/application.yml
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    network_mode: bridge

