server:
    port: 29223

redisson:
    keyPrefix:
    threads: 4
    nettyThreads: 8
    singleServerConfig:
        clientName: pter
        connectionMinimumIdleSize: 8
        connectionPoolSize: 32
        idleConnectionTimeout: 10000
        timeout: 3000
        subscriptionConnectionPoolSize: 50


pter:
    # 官种页面（带排序参数,按照做种人数升序）
    url: https://pterclub.com/officialgroup.php?inclbookmarked=0&incldead=1&spstate=2&&sort=7&type=asc&tag_internal=yes&page=
    # cookie【需要修改】
    cookie: xxxx
    # 单种最大体积（MB）【需要修改】
    maxDefendSize: 900
    # qb保种标签
    tag: pter
    # 单种最小保种人数【需要修改】
    minSeeder: 1
    # 单种最大保种人数【需要修改】
    maxSeeder: 5
    # 猫站4小时流控数量【需要修改】
    maxTorrentStopCnt: 80


qbittorrent:
    # qb地址【需要修改】
    url: http://192.168.3.10:8085
    # 用户名【需要修改】
    username: admin
    # 密码【需要修改】
    password: admin
    # 保存路径【需要修改】
    savePath: /pt/pter
    # 最大上传速度（MB）
    uploadLimit: 50
    # 最大下载传速度（MB）
    downloadLimit: 50

spring:
    redis:
        # 地址【需要修改】
        host: 192.168.3.10
        # 端口，默认为6379【需要修改】
        port: 6379
        # 数据库索引
        database: 0
        # 密码(如没有密码请注释掉)
        # password:
        # 连接超时时间
        timeout: 10s
        # 是否开启ssl
        ssl: false

quartz:
    # 时间正则（每小时一次）
    cron: 0 10 0/1 * * ?
    # 98时间正则
    shtcron: 0 35 1 * * ?
    # 删猫站删种信息
    delptermsgcron: 0 20 0/4 * * ?
    # tr删除猫ban种
    trdelbancron: 0 35 2 * * ?

tr:
    # tr地址【需要修改】
    url: http://192.168.3.10:9091
    # 用户名【需要修改】
    username: admin
    # 密码【需要修改】
    password: admin
    # 错误信息包含（多个用分号分割）【需要修改】
    errorMsg: err torrent banned;torrent does not exist

sht:
    url: https://1kdj5.app/
    cookie: xxxxx
    # 英文;分割
    replyMsgs: 身材很好啊;感觉要被榨干;怎一个6字了得;妹子真不错;感觉要精尽人亡了;看着感觉很顶啊;就喜欢这种类型的
